language: go
go: 
 - "1.11.x"

os: osx

install: true

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN="d9d971f2-368d-46b7-ab06-f605ef2bdb10"

addons:
  ssh_known_hosts:
  - github.com
  - ssh.github.com

before_install:
  - >-
    openssl aes-256-cbc 
    -K $encrypted_84c1f1c63f6c_key
    -iv $encrypted_84c1f1c63f6c_iv 
    -in vstsdk_rsa.enc 
    -out vstsdk_rsa 
    -d
  - chmod 600 vstsdk_rsa
  - eval $(ssh-agent -s)
  - ssh-add vstsdk_rsa
  # dependencies
  - git clone ssh://git@github.com/dudk/vst2sdk.git
  - brew install portaudio lame

script: env CGO_CFLAGS=-I$(pwd)/vst2sdk go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)